[package]
name = "hx_diff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git_cli_wrap = { path = "../git_cli_wrap" }

clap = { version = "4.5.4", features = ["derive"] }
similar = "2.5.0"

gpui = { git = "https://github.com/zed-industries/zed", rev = "d2569afe662be93c926eed1aeb2b17d050ba90b0" }
theme = { git = "https://github.com/zed-industries/zed", rev = "d2569afe662be93c926eed1aeb2b17d050ba90b0" }
settings = { git = "https://github.com/zed-industries/zed", rev = "d2569afe662be93c926eed1aeb2b17d050ba90b0" }
assets = { git = "https://github.com/zed-industries/zed", rev = "d2569afe662be93c926eed1aeb2b17d050ba90b0" }
ui = { git = "https://github.com/zed-industries/zed", rev = "d2569afe662be93c926eed1aeb2b17d050ba90b0" }
